<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_OrderComment
 * @copyright   Copyright (c) 2023 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

/** @var \Magento\Backend\Block\Template $block */

if ($comment = $block->getOrderComment()) :?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= __('Order Comment') ?></span>
        </div>
        <div class="admin__page-section-content">
            <?php echo nl2br($block->escapeHtml($comment));?>
        </div>
    </section>
<?php endif; ?>
